Хелпер для загрузки BSL LS
1c-syntax/utils pull request #3
Opened 2020-06-22 18:05 UTC by otymko

2020-07-04 09:58 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/utils/DownloadHelper.java
> +  private Optional<GHRelease> getLatestRelease(GHRepository repo, boolean prerelease) throws IOException {
вот эта логика не совсем верная. если ты посмотришь в реализацию загрузчика для vsc, то в случае если запрашивается последний релиз по каналу prerelease, если релиз вышел после пререлиза, то вернется релиз. а в твоем коде - пререлиз.

2020-07-04 09:59 UTC, nixel2007 requested changes
latest prerelease

2020-07-04 14:15 UTC, otymko commented on src/main/java/com/github/_1c_syntax/utils/DownloadHelper.java
> +  private Optional<GHRelease> getLatestRelease(GHRepository repo, boolean prerelease) throws IOException {
Спасибо! Посмотрю

2021-07-14 12:30 UTC, nixel2007 commented
драфт/не драфт?

2021-09-14 13:37 UTC, otymko commented
@nixel2007 вернусь к реквесту через неделю

2026-07-04 05:04 UTC, closed without merging